hughsie/libjcat

- data/tests/colorhug/meson.build
- data/tests/pki/meson.build
- libjcat/jcat-self-test.c
- libjcat/meson.build
- meson.build
If the source or build directory is not available then it currently fails,
which isn't the idea of installed tests at all...
Also, as we're here, make the build 100% reproducable by sharing the build dir
as an environment variable to the local tests rather than a cflag.
To run the installed tests users can use:
gnome-desktop-testing-runner libjcat/libjcat.test
Fixes https://github.com/hughsie/libjcat/issues/19
> Make the installed tests actually work

- libjcat/jcat-self-test.c
Containers and minimal autobuilder environments don't always have
a systemd machine ID, or any init system or related packages at all.
There's no real reason why we need the machine ID or a file here,
and jcat_get_contents_bytes() is exercised elsewhere, so we can sign a
string from memory instead.
Fixes: https://github.com/hughsie/libjcat/issues/22
> jcat-self-test: Sign a simple string instead of /etc/machine-id

- .lgtm.yml
Loosely based on a version formerly used by systemd.
Might fix https://github.com/hughsie/libjcat/issues/21 or not, but I can't really test it without opening a PR :-)
> lgtm: Install a newer Meson version using pip

- libjcat/meson.build
By default, _i.e._ when executed directly, _generate-version-script.py_ uses /usr/bin/python3, whatever version that may be - which causes problems if the default python3 installation either is built without XML support or does not provide setuptools. Make sure the script is invoked using the same interpreter as meson itself, as that one is already guaranteed to provide both 'xml' and 'pkg_resources'.
> meson: Run generate-version-script.py using the same Python as meson itself

- libjcat/jcat-file.c
- libjcat/jcat-item.c
- libjcat/jcat-item.h
- libjcat/jcat-self-test.c
- libjcat/jcat-tool.c
- libjcat/jcat.map
This allows us to still validate when we have to rename the file we want to
validate. Typically this would be used when the client software is expecting
an ID of `payload.xml` but we sign something called `payload-{date}.xml`.
> Allow adding an item ID 'alias'

- libjcat/meson.build
This hopefully fixes the build on Darwin.
> build: Only pass --version-script to linker when supported

- libjcat/meson.build
It is not true that Meson's Python will always have setuptools as that is only required during build.
See https://discuss.python.org/t/build-system-and-undeclared-dependency-on-it-during-runtime/2455
To be sure, let's check for the required modules explicitly.
cc @mkszuba
> build: Check for Python modules explicitly

- libjcat/jcat-engine.c
Fixes https://github.com/fwupd/fwupd/issues/2223#issuecomment-649491960
> Export the old JCatEngine property to preserve internal ABI

- libjcat/jcat-context.c
libjcat can be compiled with both gpg and pkcs7, but if it's compiled
without one then blobs signed with both can't be verified.
```
Jcat engine kind 'gpg' not supported
```
> jcat-context: don't fail verification if compiled without an engine

- libjcat/jcat-context.c
This is the same behaviour as used in jcat_context_verify_item() but forgotten
somehow. We can only use jcat_engine_pubkey_verify() on pubkeys.
Fixes https://github.com/hughsie/libjcat/issues/47
> Fix jcat_context_verify_blob() to use self verify for checksums

- .github/workflows/ccpp.yml
- contrib/ci/Dockerfile-debian
- contrib/ci/Dockerfile-fedora
- contrib/libjcat.spec.in
- libjcat/jcat-tool.1
- libjcat/meson.build
This prevents problems when cross compiling. Using help2man is now also of
limited use; if we can just tell the user to use --help we do not need to keep
the manual in sync.
See https://github.com/fwupd/fwupd/issues/3025
> Do not use help2man to build manual pages

- libjcat/jcat-tool.c
This only affect using jcat-tool, jcat_context_verify_item() already
skips disabled engines and only returns failure if nothing can verify
the signature.
> Show a more accurate output when not all engines are enabled

- libjcat/meson.build
When the first argument to python.find_installation is omitted, Meson will return the Python instance used to run it. But that can be a completely different installation than the one on PATH.
This change was initially introduced in https://github.com/hughsie/libjcat/commit/cf2d9298a5fab7278ee040bc0b4be384a7b5538e but reverted in https://github.com/hughsie/libjcat/commit/98e5b9060fd2a96d707a449635e13b5b2ffc1ecc due to concern about FreeBSD 12.2. But FreeBSD 12.2 installs python3 on PATH nowadays and even if it did not, the inability to find Python is a [bug to fix in Meson](https://github.com/mesonbuild/meson/issues/4608).
cc @Asiderr (for https://github.com/hughsie/libjcat/pull/52)
> build: Require Python explicitly

- contrib/generate-version-script.py
- libjcat/meson.build
The python module's find_installation method is incorrect -- it does a variety of things geared towards building and installing python modules into site-packages. This is slow and inefficient and completely pointless -- all that is needed here is to run scripts.
find_program() is guaranteed to find the python3 interpreter too, and is the correct way to find any other program, so use it for python as well.
> meson: use the correct lookup method for the python3 script interpreter

- data/tests/meson.build
- libjcat/jcat-self-test.c
The Apple certtool and GnuTLS certtool have different CLI options.
> Fix incorrect certtool being called on macOS

- contrib/build-certs.py
This ensures that, no matter the local timezone, the certificates will be active as of the current time on the local machine.
This resolved #65 for me.
> predate test cert activation date by 1 day

- data/tests/colorhug/meson.build
This was forgotten in f802f078ec0349e4056bf764ee4da16fe9973978.
> installed-tests: install firmware.bin.ed25519

- libjcat/jcat-item.c
PVS: The conditional expressions of the 'if' statements situated alongside each other are identical.
> Correctly export the AliasIds in all cases

- libjcat/jcat-blob.c
- libjcat/jcat-blob.h
- libjcat/jcat-sha512-engine.c
- libjcat/jcat-sha512-engine.h
- libjcat/jcat-tool.c
- libjcat/meson.build
This allows us to deprecate SHA-1 and still have two different checksum types.
> Add support for SHA512 checksums

- libjcat/jcat-version.h.in
This fixes a warning about exported prefixes in gtk-doc.
> Fix prefix of LIBJCAT_CHECK_VERSION

- libjcat/jcat-ed25519-engine.c
```
[18/43] Compiling C object libjcat/cygjcat-1.dll.p/jcat-ed25519-engine.c.o
../libjcat/jcat-ed25519-engine.c: In function ‘jcat_ed25519_sig_from_bytes’:
../libjcat/jcat-ed25519-engine.c:42:9: warning: implicit declaration of function ‘memcpy’ [-Wimplicit-function-declaration]
42 |         memcpy(privkey, g_bytes_get_data(blob, NULL), sizeof(Ed25519Sig));
|         ^~~~~~
../libjcat/jcat-ed25519-engine.c:15:1: note: include ‘<string.h>’ or provide a declaration of ‘memcpy’
14 | #include "jcat-engine-private.h"
+++ |+#include <string.h>
15 |
../libjcat/jcat-ed25519-engine.c:42:9: warning: incompatible implicit declaration of built-in function ‘memcpy’ [-Wbuiltin-declaration-mismatch]
42 |         memcpy(privkey, g_bytes_get_data(blob, NULL), sizeof(Ed25519Sig));
|         ^~~~~~ …
```
> Fix header includes

- libjcat/jcat-bt-proof.c
- libjcat/jcat-bt-util.c
- libjcat/jcat-common-private.h
- libjcat/jcat-common.c
- libjcat/jcat-self-test.c
The function `jcat_bt_inmemory_tree_recompute_past_snapshot` is called for its output parameter, but previously its return value was simply dropped instead of unref()'ed.
> Fix various memory leaks

- libjcat/jcat-common-private.h
- libjcat/jcat-common.c
- libjcat/jcat-ed25519-engine.c
- libjcat/jcat-pkcs7-engine.c
- libjcat/jcat-tool.c
Althouth it's only used for self-signing in fwupd, it's probably not a good idea to make this world-readable by default. If nothing else it'll make some EDR happy somewhere.
Fixes https://github.com/hughsie/libjcat/issues/129
> Save the auto-generated private key with 0600 file permissions

- libjcat/jcat-ed25519-engine.c
- libjcat/jcat-self-test.c
- meson.build
Previously, libjcat linked to both GnuTLS and Nettle for ED25519
support, though it can be implemented sorely with GnuTLS. This patch
drops the direct usage of Nettle for simplicity and better ABI
compatibility, as Nettle occasionally bumps library SONAME which
requires rebuild of the binary[1].
1. https://www.lysator.liu.se/~nisse/nettle/nettle.html#Compatibility
> Switch ED25519 support to not directly using Nettle

- libjcat/jcat-self-test.c
Otherwise it fails with "jcat-self-test.c:1147:jcat_bt_common_func: assertion failed (error == NULL): Jcat engine kind 'ed25519' not supported (g-io-error-quark, 1)"
> Skip ed25519 part of a test with -Ded25519=false

- libjcat/meson.build
Currently the build fails if you configure it with `-Dgnutls_ed25519=true -Dgnutls_pkcs7=false`.
> trivial: Include jcat-gnutls-common.c when compiling ed25519

- libjcat/jcat-self-test.c
During a self test run the client certificates are created in `/tmp/pki/{secret,client}.pem`. There keys are reused on subsequent runs and RSA keypair generation isn't tested.
This branch adds a temporary directory which allows for testing key generation on every run and tests whether a signature can be validated with an incorrect key.
It also tests whether a signature will validate an incorrect payload.
> jcat-self-test/pkcs7: more fail cases, test RSA gen
